version: '2'
services:
  cassandradynamoldap-app:
    image: cassandradynamoldap
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_CASSANDRA_CONTACTPOINTS=cassandradynamoldap-cassandra
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
    ports:
      - 8080:8080
  cassandradynamoldap-cassandra:
    extends:
      file: cassandra-cluster.yml
      service: cassandradynamoldap-cassandra
  cassandradynamoldap-cassandra-node:
    image: cassandra:3.11.5
    environment:
      - CASSANDRA_SEEDS=cassandradynamoldap-cassandra
  cassandradynamoldap-cassandra-migration:
    extends:
      file: cassandra-migration.yml
      service: cassandradynamoldap-cassandra-migration
    environment:
      - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
